version: '2'
services:
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    restart: unless-stopped
    environment:
      - API_KEY=${CF_API_KEY}
      - ZONE=${CF_ZONE}
      - PROXIED=false
